### ISSUE TITLE
unstable trajectory

### ISSUE THREAD

**Issue by charlie-dog** [HKUST-Aerial-Robotics/FALCON#2]
![image](https://github.com/user-attachments/assets/4d9907da-bc6a-4ec1-b29d-24e44e01332a)
The trajectory is very unstable. The acceleration significantly exceeds the threshold.

**Comment by charlie-dog** [comment]
Moreover, the yaw velocity is discontinuous, making it difficult to be deployed on rotors. 
![image](https://github.com/user-attachments/assets/62a876bf-4855-4ce9-88f7-bf5cb715d26b)

**Comment by yzhangec** [comment]
should be fixed in latest commit 7f7983c

**Comment by charlie-dog** [comment]
@yzhangec It works! Thank you bro!
