### ISSUE TITLE
about pcd file type

### ISSUE THREAD

**Issue by endlesmoon** [HKUST-Aerial-Robotics/FALCON#3]
Why do I get stuck here when I start FALCON with the pcd file suffix，just like roslaunch exploration_manager exploration.launch map_name:="classical_office",but when I use stl,it can normal run
![2024-12-27 18-46-36 的屏幕截图](https://github.com/user-attachments/assets/6040854e-67f3-4297-ae0b-36c8910ccbd0)

**Comment by endlesmoon** [comment]
![2024-12-27 23-54-53 的屏幕截图](https://github.com/user-attachments/assets/83e010ad-86d0-4827-92d9-a5a52ecac279)
and this is map_server error ,I'm still try a way to solve it

**Comment by eehantiming** [comment]
hi @endlesmoon, i am facing the same problem, can you share the fix?

**Comment by endlesmoon** [comment]
> hi [@endlesmoon](https://github.com/endlesmoon), i am facing the same problem, can you share the fix?

sorry,I didn't fix it,I just use pointcloud rostopic replace,but when I use https://github.com/SYSU-STAR/RACER ,this way also use pcd type to generate map ,i still find that I can't make the right planning , maybe we can find the answer from them,If you find a solution, I hope you can share it with me！！！

**Comment by Alex-Jagger** [comment]
@endlesmoon I think I encountered the same issue as you guys. I fixed it by ensuring the CUDA arch and code number are correct. I am using a GTX 1660 super; the original code was for Titan XP. Make sure that number matches your GPU well. The pointcloud map is rendered by opencv so it needs an Nvidia GPU. catkin_make won't throw an error if the arch number doesn't match your GPU.

**Comment by endlesmoon** [comment]
@Alex-Jagger thanks! I will try later

**Comment by gaoyuxiang-seu** [comment]
hi! im meeting the same problem ,have you fixed it now?   😊

**Comment by Babyfishking** [comment]
> 你好！我遇到了同样的问题，你现在解决了吗？😊
我也遇到了这一问题
